builds:
  - binary: mackerel-plugin-aws-ec2
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: mackerelio
    name: mackerel-plugin-aws-ec2
