#!/bin/sh

# Usage:
# $ script/release # Setting github.token in .gitconfig is required
# $ GITHUB_TOKEN=... script/release

set -e
latest_tag=$(git describe --abbrev=0 --tags)
echo $latest_tag
goxc --version

ghr --version
